url: "https://allanmodc.github.io/cfd" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
feed_icon: /assets/images/icon-512.png
twitter_username: allanmodc
github_username:  allanmodc
hide_credits: true

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 20
paginate_path: "/page/:num/"
